# Generated by Django 4.1.7 on 2023-02-27 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalAdmin', '0003_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
