# Generated by Django 4.1.7 on 2023-02-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalAdmin', '0005_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='yearFounded',
            field=models.CharField(default='01-01-2001', max_length=10),
        ),
    ]
