# Generated by Django 4.1.7 on 2023-02-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalAdmin', '0008_alter_employees_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='empNo',
            field=models.BigIntegerField(),
        ),
    ]
