# Generated by Django 4.1.7 on 2023-02-28 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalAdmin', '0009_alter_employees_empno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='empNo',
        ),
    ]
