# Generated by Django 4.1.7 on 2023-03-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalAdmin', '0010_remove_employees_empno'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='description',
            field=models.CharField(default='headuser', max_length=255),
        ),
    ]
